version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: hugo123
      POSTGRES_USER: postgres
      POSTGRES_DB: rpg
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
  backend:
    platform: linux/amd64
    image: node:20-alpine
    working_dir: .
    tty: true
    depends_on:
      - db
    ports:
      - '3333:3333'
    volumes:
      - ../:/projects
    command: apt-get update && apt-get install -y build-essential && apt-get install -y python
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: hugo123
      POSTGRES_USER: postgres
      POSTGRES_DB: rpg
      POSTGRES_PORT: 5432
      PORT: 3333
      HOST: 0.0.0.0
      SECRET_KEY: secret

